#!/usr/bin/env bash
# Installing nginx on our webserver
sudo apt-get update -y
sudo apt-get install nginx -y
sudo chown $USER:$USER /var/www/html/index/html
echo "Hello World!" > /var/www/html/index.html
service ngninx restart