#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server.

sudo apt install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.4 -y
sudo apt update
sudo apt install haproxy=2.4.\*

load_balancer="\nfrontend http\n
\tbind *:80
\tmode http
\tdefault_backend load_b

backend load_b\n
\tbalance roundrobin
\tserver web-01 18.206.232.128 check
\tserver web-02 100.25.162.95 check
"
echo -e "ENABLED=1\n" | sudo tee -a /etc/default/haproxy
echo -e "$load_balancer" | sudo tee -a /etc/haproxy/haproxy.cfg

service haproxy restart
