#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.
chmod 777 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill -9 apache
sudo nginx -c "service nginx restart"